alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: pythonwebapps-student-week-9-new
    match:
      path:
        prefix: /
  - component:
      name: pythonwebapps-student-week-9-ne2
    match:
      path:
        prefix: /static
name: coral-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_ENGINE
    scope: RUN_AND_BUILD_TIME
    value: django.db.backends.sqlite3
  - key: DJANGO_SUPERUSER_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: garz7950@bears.unco.edu
  - key: DJANGO_SUPERUSER_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: Daniel
  - key: DJANGO_SUPERUSER_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:H3m/s8J0fo27tY7NqPMHFGeoDeNXEqp9:KfCPVqjVRKylIMiUOfrVskX40vLl2xoAQbzL2gc=]
  github:
    branch: main
    deploy_on_push: true
    repo: ssjdan27/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: pythonwebapps-student-week-9-new
  run_command: |-
    python manage.py createsuperuser --noinput
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Student/week11/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: ssjdan27/PythonWebApps
  name: pythonwebapps-student-week-9-ne2
  source_dir: Student/week11/Superhero/static
