alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: pythonwebapps-student-week9-news
    match:
      path:
        prefix: /
  - component:
      name: pythonwebapps-student-week9-news
    match:
      path:
        prefix: /static
name: coral-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
  github:
    branch: main
    deploy_on_push: true
    repo: ssjdan27/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: pythonwebapps-week9-news
  run_command: gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Student/week9/News
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: ssjdan27/PythonWebApps
  name: pythonwebapps-student-week9-news
  source_dir: Student/week9/News/static
