# Generated by Django 5.1.2 on 2024-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_photo_superhero_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
