# Generated by Django 5.1.2 on 2024-11-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="news.article",
            ),
            preserve_default=False,
        ),
    ]
