# Generated by Django 5.1.2 on 2024-11-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_photo_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="news.article",
            ),
        ),
    ]
